//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOnline.module {
    
    
    public partial class baocaogiamsatdautu {
        
        /// <summary>
        /// hdfsttBCGSDauTuCTpr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdfsttBCGSDauTuCTpr;
        
        /// <summary>
        /// Grid_ChuTruongDauTu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Grid.Grid Grid_ChuTruongDauTu;
        
        /// <summary>
        /// Window3DuAn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Window.Window Window3DuAn;
        
        /// <summary>
        /// btnChon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton btnChon;
        
        /// <summary>
        /// btnThoat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton btnThoat;
        
        /// <summary>
        /// Grid1_duAn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Grid.Grid Grid1_duAn;
        
        /// <summary>
        /// idDialogYesNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Window.Dialog idDialogYesNo;
        
        /// <summary>
        /// btnDongY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton btnDongY;
        
        /// <summary>
        /// btnHuy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton btnHuy;
    }
}
