//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOnline.module {
    
    
    public partial class canhan {
        
        /// <summary>
        /// winDowThemCaNhan_maCaNhanpr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_maCaNhanpr;
        
        /// <summary>
        /// winDowThemCaNhan_tenCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_tenCaNhan;
        
        /// <summary>
        /// winDowThemCaNhan_chucVuCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_chucVuCaNhan;
        
        /// <summary>
        /// winDowThemCaNhan_dienThoaiCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_dienThoaiCaNhan;
        
        /// <summary>
        /// winDowThemCaNhan_maToChucpr_sd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox winDowThemCaNhan_maToChucpr_sd;
        
        /// <summary>
        /// winDowThemCaNhan_gioiTinhCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox winDowThemCaNhan_gioiTinhCaNhan;
        
        /// <summary>
        /// winDowThemCaNhan_ngaySinhCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_ngaySinhCaNhan;
        
        /// <summary>
        /// Calendar6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Calendar2.Calendar Calendar6;
        
        /// <summary>
        /// winDowThemCaNhan_diaChiCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_diaChiCaNhan;
        
        /// <summary>
        /// winDowThemCaNhan_CMNDCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_CMNDCaNhan;
        
        /// <summary>
        /// winDowThemCaNhan_ngayCapCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_ngayCapCaNhan;
        
        /// <summary>
        /// Calendar7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Calendar2.Calendar Calendar7;
        
        /// <summary>
        /// winDowThemCaNhan_noiCapCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemCaNhan_noiCapCaNhan;
    }
}
