//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOnline.module {
    
    
    public partial class tochuc {
        
        /// <summary>
        /// winDowThemToChuc_MaToChucpr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_MaToChucpr;
        
        /// <summary>
        /// winDowThemToChuc_tenToChuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_tenToChuc;
        
        /// <summary>
        /// winDowThemToChuc_maToChucpr_sd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox winDowThemToChuc_maToChucpr_sd;
        
        /// <summary>
        /// winDowThemToChuc_diaChi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_diaChi;
        
        /// <summary>
        /// winDowThemToChuc_maSoThue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_maSoThue;
        
        /// <summary>
        /// winDowThemToChuc_dienThoaiToChuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_dienThoaiToChuc;
        
        /// <summary>
        /// winDowThemToChuc_faxToChuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_faxToChuc;
        
        /// <summary>
        /// winDowThemToChuc_emailToChuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_emailToChuc;
        
        /// <summary>
        /// winDowThemToChuc_daiDienToChuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_daiDienToChuc;
        
        /// <summary>
        /// winDowThemToChuc_chucVuDaiDien control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_chucVuDaiDien;
        
        /// <summary>
        /// winDowThemToChuc_nguoiLienHe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_nguoiLienHe;
        
        /// <summary>
        /// winDowThemToChuc_chucVuLienHe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_chucVuLienHe;
        
        /// <summary>
        /// winDowThemToChuc_dienThoaiLienHe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox winDowThemToChuc_dienThoaiLienHe;
    }
}
