//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOnline.module {
    
    
    public partial class vanban_buocketthuc {
        
        /// <summary>
        /// sttVBDApr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField sttVBDApr;
        
        /// <summary>
        /// hdfTenForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdfTenForm;
        
        /// <summary>
        /// txtSoVanBan_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtSoVanBan_uc;
        
        /// <summary>
        /// txtNgayKy_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtNgayKy_uc;
        
        /// <summary>
        /// Calendar_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Calendar2.Calendar Calendar_uc;
        
        /// <summary>
        /// cboCoQuanBanHanh_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox cboCoQuanBanHanh_uc;
        
        /// <summary>
        /// cboNguoiKy_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox cboNguoiKy_uc;
        
        /// <summary>
        /// txtChucDanh_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtChucDanh_uc;
        
        /// <summary>
        /// cboLoaiVanBan_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox cboLoaiVanBan_uc;
        
        /// <summary>
        /// txtNoiDung_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtNoiDung_uc;
        
        /// <summary>
        /// txtGiaTri_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtGiaTri_uc;
        
        /// <summary>
        /// ToolkitScriptManager_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager_uc;
        
        /// <summary>
        /// AsyncFileUpload_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AsyncFileUpload AsyncFileUpload_uc;
        
        /// <summary>
        /// WindowCQBH_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Window.Window WindowCQBH_uc;
        
        /// <summary>
        /// bttLuuvaDongCN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton bttLuuvaDongCN;
        
        /// <summary>
        /// bttDongCN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton bttDongCN;
        
        /// <summary>
        /// txtMa_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtMa_uc;
        
        /// <summary>
        /// txtTen_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtTen_uc;
        
        /// <summary>
        /// cboThuocNhomToChuc_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.ComboBox.ComboBox cboThuocNhomToChuc_uc;
        
        /// <summary>
        /// txtDiaChi_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtDiaChi_uc;
        
        /// <summary>
        /// txtMaSoThue_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtMaSoThue_uc;
        
        /// <summary>
        /// txtDienThoai_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtDienThoai_uc;
        
        /// <summary>
        /// txtFax_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtFax_uc;
        
        /// <summary>
        /// txtEmail_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtEmail_uc;
        
        /// <summary>
        /// txtNguoiDaiDien_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtNguoiDaiDien_uc;
        
        /// <summary>
        /// txtChucVuDaiDien_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtChucVuDaiDien_uc;
        
        /// <summary>
        /// txtNguoiLienHe_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtNguoiLienHe_uc;
        
        /// <summary>
        /// txtChucVuLienHe_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtChucVuLienHe_uc;
        
        /// <summary>
        /// txtDienThoaiToChuc_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutTextBox txtDienThoaiToChuc_uc;
        
        /// <summary>
        /// winDowThemCaNhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.Window.Window winDowThemCaNhan;
        
        /// <summary>
        /// OboutButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton OboutButton1;
        
        /// <summary>
        /// OboutButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Obout.Interface.OboutButton OboutButton2;
        
        /// <summary>
        /// canhan_uc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProOnline.module.canhan canhan_uc;
    }
}
